// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/Shared/ActionButton.vue')['default']
    DarkSwitcher: typeof import('./components/DarkSwitcher.vue')['default']
    JobSearchForm: typeof import('./components/JobSearch/JobSearchForm.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    MainNav: typeof import('./components/Navigation/MainNav.vue')['default']
    NavBar: typeof import('./components/__tests__/NavBar.vue')['default']
    ProfileImage: typeof import('./components/Navigation/ProfileImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubNav: typeof import('./components/Navigation/SubNav.vue')['default']
    TextInput: typeof import('./components/Shared/TextInput.vue')['default']
    TheHeadline: typeof import('./components/JobSearch/TheHeadline.vue')['default']
    TheHero: typeof import('./components/JobSearch/TheHero.vue')['default']
  }
}

export {}
